version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "06:00"
    timezone: "Asia/Kolkata"
  labels:
    - "dependencies"
  open-pull-requests-limit: 20
  ignore:
    - dependency-name: "sqlalchemy"
    # Ignoring all sql updates
    - dependency-name: "python-telegram-bot"
    # Ignoring all ptb updates
    - dependency-name: "aiohttp"
    # Ignoring all aiohttp updates
    - dependency-name: "pyrogram"
    # Ignoring all pyrogram updates
